<template><div><img src="https://wfqqreader-1252317822.image.myqcloud.com/cover/871/33603871/t6_33603871.jpg" alt="书籍封面" class="wr_bookCover_img">
<p>半小时漫画预防常见病
陈磊·半小时漫画团队</p>
<p>简介：</p>
<p>《半小时漫画预防常见病》是陈磊（笔名：二混子）又一科普大作！稍稍改变生活习惯，轻松扫除常见病隐患！用爆笑漫画讲清复杂的疾病成因，嘻嘻哈哈中学会科学预防常见病！华山医院感染科主任医师，急诊科主任陈明泉审校！摸清常见病成因，做自己的医生。介绍了十二种常见病的发病机理，以及要想预防这些疾病，我们的生活习惯需要做哪些小改变。饭前便后、外出回家，如果能洗一次手，就能降低手足口病、新冠肺炎等疾病的感染风险；预防小儿麻痹症和禽流感等疾病，切记不吃生食不喝生水；不要胡吃海喝，小心糖尿病和酒精肝找上门；不要熬夜，充足睡眠，提高免疫力，流感就会绕着你走……翻开本书，摸清常见病成因，做自己的医生。</p>
<p>26个想法</p>
<p>◆ 一、流感肆虐，你中招了吗</p>
<blockquote>
<blockquote>
<p>神经系统会立马让人发抖、发热，因为病毒在高温下会没了兴致，也就生不了孩子。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>这就是为什么感冒时觉得浑身无力，因为身体正把能量调到战场，准备与病毒厮杀。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>记住哦，大多数情况下，吃药只能缓解你的症状，让你感觉舒服一些。</p>
</blockquote>
</blockquote>
<p>◆ 三、艾滋病的故事</p>
<blockquote>
<blockquote>
<p>HIV本身不致命，但它会破坏免疫系统，引发其他疾病：各种感染(病毒感染、细菌感染、真菌感染等)和肿瘤。</p>
</blockquote>
</blockquote>
<p>◆ 四、小儿麻痹症到底是咋回事</p>
<blockquote>
<blockquote>
<p>在没有疫苗的情况下，我们的免疫系统需要两周到一个月才能大规模识别脊髓灰质炎病毒。</p>
</blockquote>
</blockquote>
<p>◆ 六、糖尿病为什么可怕</p>
<blockquote>
<blockquote>
<p>如果血糖过多，剩余的血糖就会跑到肝脏去度假，这就是肝糖原。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>视网膜和肾</p>
</blockquote>
</blockquote>
<p>◆ 七、不穿秋裤，真的会得“风湿病”吗</p>
<blockquote>
<blockquote>
<p>这时，滑膜里就会大量堆积抗体和炎症因子，最后导致滑膜不断增生</p>
</blockquote>
</blockquote>
<p>◆ 八、贫血是咋回事都不清楚就瞎补</p>
<blockquote>
<blockquote>
<p>贫血指的就是红细胞少于正常数量。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>很多原因都可以让免疫系统发疯，六亲不认，比如病毒感染。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>再生障碍性贫血</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>溶血性贫血</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>因为缺铁导致的贫血叫缺铁性贫血，是最常见的贫血。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>溶血时，死掉的红细胞小哥会释放一种叫胆红素的东西，过多就会染黄眼睛或皮肤，造成黄疸现象。</p>
</blockquote>
</blockquote>
<p>◆ 九、新型冠状病毒究竟是啥玩意儿</p>
<blockquote>
<blockquote>
<p>我们的细胞又名“宇宙蛋白质加工制造有限责任公司”，它就是个大厂房，设备齐全，负责生产各种蛋白质送到全身。</p>
</blockquote>
</blockquote>
<p>◆ 十、世界上本没有酒精肝，喝得多了，便有了酒精肝</p>
<blockquote>
<blockquote>
<p>本来肝脏还要处理身体里的油脂，但因为乙醛捣乱，肝细胞顾不上油脂，油脂就开始捣乱了。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>乙醛会直接损伤肝细胞，使肝细胞无法正常代谢油脂，从而形成酒精性脂肪肝，即酒精肝。</p>
</blockquote>
</blockquote>
<p>◆ 十一、天天喊HPV，你搞清楚宫颈癌是什么了吗</p>
<blockquote>
<blockquote>
<p>HPV，全名叫人乳头状瘤病毒，它最喜欢寄居在人体各处的表皮里</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>皮肤上鼓起了一个包，那就是瘤啊!这就造成了宫颈上皮内瘤变。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>这些高仿但没杀伤力的HPV就叫HPV疫苗。能杀几种HPV的疫苗就叫几价疫苗。</p>
</blockquote>
</blockquote>
<p>◆ 十二、不了解乳房，怎么预防乳腺癌</p>
<blockquote>
<blockquote>
<p>排卵后激素水平会快速上升，造成乳腺组织略微变大，为怀孕做准备。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>顺带一说，激素水平的下降，同时也给姑娘们带来了另一位老朋友，它就是——[插图]大姨妈!</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>婴儿的吮吸会让乳腺分泌更多的乳汁。可如果一不小心产量太高，乳管就可能会堵住。乳汁出不去，细菌就生出来了。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>于是乳腺车间的员工增多，就造成了乳腺增生。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>乳腺增生是最常见的乳腺疾病，包括乳房肿块、囊肿、纤维瘤等。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>其实多数激素的背后都有一个操控者，隐居在大脑里，叫促性腺激素释放激素，简称GnRH。</p>
</blockquote>
</blockquote>
</div></template>


